package grantex

import (
	"context"
	"encoding/json"
	"os"
	"path/filepath"
	"sort"
	"strings"
	"testing"
)

// testdata/signing-keys-legacy-kid.json is a copy of
// spec/examples/signing-keys-legacy-kid.json, generated by the auth service:
// its JWK Set on 2026-09-01 and tokens signed by its keys, including a pre-0.6
// token signed on 2026-08-31 with kid grantex-2026-08. The copy keeps these
// tests runnable outside the monorepo.
type servedKeysFixture struct {
	Issuer string `json:"issuer"`
	JWKS   struct {
		Keys []map[string]interface{} `json:"keys"`
	} `json:"jwks"`
	Tokens map[string]struct {
		Kid   string `json:"kid"`
		Alg   string `json:"alg"`
		Token string `json:"token"`
	} `json:"tokens"`
	Claims map[string]interface{} `json:"claims"`
}

func TestServedKeysFixtureMatchesTheSpecExample(t *testing.T) {
	spec, err := os.ReadFile(filepath.FromSlash("../../spec/examples/signing-keys-legacy-kid.json"))
	if os.IsNotExist(err) {
		t.Skip("spec/examples is not present outside the monorepo")
	}
	if err != nil {
		t.Fatalf("read spec example: %v", err)
	}
	local, err := os.ReadFile(filepath.Join("testdata", "signing-keys-legacy-kid.json"))
	if err != nil {
		t.Fatalf("read testdata copy: %v", err)
	}
	normalize := func(b []byte) string { return strings.ReplaceAll(string(b), "\r\n", "\n") }
	if normalize(spec) != normalize(local) {
		t.Fatal("testdata/signing-keys-legacy-kid.json differs from spec/examples; copy the spec example")
	}
}

func TestTokensVerifyAgainstTheJWKSetTheAuthServiceServes(t *testing.T) {
	raw, err := os.ReadFile(filepath.Join("testdata", "signing-keys-legacy-kid.json"))
	if err != nil {
		t.Fatalf("read fixture: %v", err)
	}
	var fixture servedKeysFixture
	if err := json.Unmarshal(raw, &fixture); err != nil {
		t.Fatalf("parse fixture: %v", err)
	}
	server := serveKeys(t, fixture.JWKS.Keys...)
	names := make([]string, 0, len(fixture.Tokens))
	for name := range fixture.Tokens {
		names = append(names, name)
	}
	sort.Strings(names)
	for _, name := range names {
		entry := fixture.Tokens[name]
		t.Run(name, func(t *testing.T) {
			grant, err := VerifyGrantToken(context.Background(), entry.Token, VerifyOptions{JwksURI: server.URL, Issuer: fixture.Issuer})
			if err != nil {
				t.Fatalf("verify %s (kid %s): %v", name, entry.Kid, err)
			}
			if grant.GrantID != fixture.Claims["grnt"] || grant.PrincipalID != fixture.Claims["sub"] {
				t.Fatalf("unexpected grant: %+v", grant)
			}
		})
	}
}
